// ============================================================
// Campos compartidos para enlaces de sub-páginas Participa
// ============================================================

const enlaceFields = [
  { name: "texto", label: "Texto del enlace", widget: "string", required: true },
  { name: "url", label: "URL", widget: "string", required: true },
  { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "pdf", "xlsx", "external", "form", "video"], default: "internal" },
  { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
];

export const participa = {
  name: "participa",
  label: "PARTICIPA",
  files: [
    {
      name: "participa-principal",
      label: "Página Principal Participa",
      file: "src/content/pages/participa.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-people-group" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        {
          name: "secciones",
          label: "Secciones de Participa",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "descripcion", label: "Descripción corta", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: true },
            { name: "url", label: "URL de la sección", widget: "string", required: true },
            { name: "color", label: "Color (blue, green, gold, purple, navy, red)", widget: "string", default: "gold" },
          ],
        },
      ],
    },
    {
      name: "diagnostico",
      label: "Diagnóstico e Identificación de Problemas",
      file: "src/content/pages/participa/diagnostico.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-magnifying-glass-chart" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        {
          name: "enlaces",
          label: "Enlaces principales",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.texto}}",
          fields: enlaceFields,
        },
        {
          name: "cajaHerramientas",
          label: "Caja de Herramientas",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.texto}}",
          fields: enlaceFields,
        },
      ],
    },
    {
      name: "planeacion",
      label: "Planeación y Presupuesto Participativo",
      file: "src/content/pages/participa/planeacion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-chart-pie" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        { name: "nota", label: "Nota aclaratoria (opcional)", widget: "text", required: false },
        {
          name: "enlaces",
          label: "Enlaces y documentos",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.texto}}",
          fields: enlaceFields,
        },
      ],
    },
    {
      name: "consulta-ciudadana",
      label: "Consulta Ciudadana",
      file: "src/content/pages/participa/consulta-ciudadana.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-comments" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        {
          name: "contenido",
          label: "Bloques de contenido",
          widget: "list",
          label_singular: "Bloque",
          collapsed: true,
          summary: "{{fields.subtitulo}}",
          fields: [
            { name: "subtitulo", label: "Subtítulo", widget: "string", required: true },
            { name: "texto", label: "Texto", widget: "text", required: true },
          ],
        },
        {
          name: "enlaces",
          label: "Recursos y enlaces",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.texto}}",
          fields: enlaceFields,
        },
      ],
    },
    {
      name: "colaboracion",
      label: "Colaboración e Innovación",
      file: "src/content/pages/participa/colaboracion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-lightbulb" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        { name: "textoAdicional", label: "Texto adicional", widget: "text", required: false },
        {
          name: "iniciativas",
          label: "Iniciativas",
          widget: "list",
          label_singular: "Iniciativa",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "descripcion", label: "Descripción", widget: "string", required: false },
            { name: "imagen", label: "URL de imagen", widget: "string", required: false },
            { name: "enlace", label: "URL del enlace", widget: "string", required: true },
            { name: "textoEnlace", label: "Texto del botón", widget: "string", required: true },
            { name: "interno", label: "Es enlace interno", widget: "boolean", default: false, required: false },
          ],
        },
      ],
    },
    {
      name: "rendicion-cuentas",
      label: "Rendición de Cuentas",
      file: "src/content/pages/participa/rendicion-de-cuentas.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-contract" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        { name: "textoAdicional", label: "Texto adicional", widget: "text", required: false },
        {
          name: "anios",
          label: "Vigencias",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.anio}} ({{fields.documentos.length}} docs)",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "documentos",
              label: "Documentos",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "{{fields.nombre}} ({{fields.tipo}})",
              fields: [
                { name: "nombre", label: "Nombre del documento", widget: "string", required: true },
                { name: "url", label: "URL", widget: "string", required: true },
                { name: "tipo", label: "Tipo", widget: "select", options: ["pdf", "xlsx", "video", "form", "external"], default: "pdf" },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "control-social",
      label: "Control Social",
      file: "src/content/pages/participa/control-social.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-shield-halved" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: true },
        {
          name: "enlaces",
          label: "Enlaces",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.texto}}",
          fields: enlaceFields,
        },
      ],
    },
  ],
};
