export const sliders = {
  name: "sliders",
  label: "SLIDERS",
  label_singular: "Slider",
  folder: "src/content/sliders",
  create: true,
  slug: "{{slug}}",
  format: "json",
  description: "Carruseles de imagenes para diferentes secciones del sitio",
  fields: [
    { name: "name", label: "Nombre del slider", widget: "string", required: true, hint: "Nombre descriptivo (ej: Slider Principal, Noticias Destacadas)" },
    { name: "description", label: "Descripcion", widget: "string", required: false },
    { name: "autoplay", label: "Reproduccion automatica", widget: "boolean", default: true },
    { name: "interval", label: "Intervalo (milisegundos)", widget: "number", default: 5000, min: 2000, max: 15000, hint: "Tiempo entre diapositivas (5000 = 5 segundos)" },
    {
      name: "slides",
      label: "Diapositivas",
      widget: "list",
      label_singular: "Diapositiva",
      collapsed: false,
      fields: [
        { name: "image", label: "Imagen", widget: "image", required: true, hint: "Tamano recomendado: 1920x600px" },
        { name: "imageAlt", label: "Texto alternativo (accesibilidad)", widget: "string", required: true },
        { name: "title", label: "Titulo", widget: "string", required: false },
        { name: "subtitle", label: "Subtitulo", widget: "string", required: false },
        { name: "description", label: "Descripcion", widget: "text", required: false },
        { name: "link", label: "Enlace", widget: "string", required: false },
        { name: "linkText", label: "Texto del boton", widget: "string", required: false, default: "Ver mas" },
        { name: "external", label: "Enlace externo", widget: "boolean", default: false, required: false },
        { name: "overlay", label: "Filtro oscuro sobre imagen", widget: "boolean", default: true, required: false, hint: "Desactivar para mostrar la imagen sin filtro de color" },
        { name: "active", label: "Activo", widget: "boolean", default: true },
        { name: "order", label: "Orden", widget: "number", default: 0 },
      ],
    },
  ],
};
