// ============================================================
// Campos compartidos para items de transparencia
// ============================================================

const itemFields = [
  { name: "num", label: "Número (ej: 1.1)", widget: "string", required: false },
  { name: "texto", label: "Texto del enlace", widget: "string", required: true },
  { name: "url", label: "URL", widget: "string", required: false, hint: "Dejar vacío si es solo etiqueta (label)" },
  { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external", "pdf", "xlsx", "label"], default: "internal" },
  {
    name: "children",
    label: "Sub-items (opcional)",
    widget: "list",
    label_singular: "Sub-item",
    collapsed: true,
    required: false,
    summary: "{{fields.num}} {{fields.texto}}",
    fields: [
      { name: "num", label: "Número", widget: "string", required: false },
      { name: "texto", label: "Texto", widget: "string", required: true },
      { name: "url", label: "URL", widget: "string", required: true },
      { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external", "pdf", "xlsx"], default: "internal" },
    ],
  },
];

export const transparencia = {
  name: "transparencia",
  label: "TRANSPARENCIA",
  files: [
    {
      name: "transparencia-principal",
      label: "Página de Transparencia",
      file: "src/content/pages/transparencia.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-eye" },
        { name: "introTexto", label: "Texto introductorio", widget: "text", required: true },
        { name: "ley1712Url", label: "URL del PDF Ley 1712", widget: "string", required: false },
        {
          name: "secciones",
          label: "Secciones de Transparencia",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.numero}}. {{fields.titulo}}",
          fields: [
            { name: "numero", label: "Número de sección", widget: "string", required: true },
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
            { name: "tituloUrl", label: "URL del título (opcional)", widget: "string", required: false },
            { name: "descripcion", label: "Descripción (opcional)", widget: "text", required: false },
            {
              name: "items",
              label: "Items",
              widget: "list",
              label_singular: "Item",
              collapsed: true,
              summary: "{{fields.num}} {{fields.texto}}",
              fields: itemFields,
            },
          ],
        },
      ],
    },
    {
      name: "directorio-entidades",
      label: "Directorio de Entidades",
      file: "src/content/pages/transparencia/directorio-entidades.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-building" },
        {
          name: "grupos",
          label: "Grupos de entidades",
          widget: "list",
          label_singular: "Grupo",
          collapsed: true,
          summary: "{{fields.nombre}} ({{fields.entidades.length}})",
          fields: [
            { name: "nombre", label: "Nombre del grupo", widget: "string", required: true },
            {
              name: "entidades",
              label: "Entidades",
              widget: "list",
              label_singular: "Entidad",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del sitio web", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "hojas-de-vida",
      label: "Publicación Hojas de Vida",
      file: "src/content/pages/transparencia/hojas-de-vida.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-id-card" },
        { name: "enlaceExterno", label: "URL enlace Presidencia", widget: "string", required: false },
        {
          name: "aspirantes",
          label: "Aspirantes",
          widget: "list",
          label_singular: "Aspirante",
          collapsed: true,
          summary: "{{fields.nombre}} — {{fields.cargo}}",
          fields: [
            { name: "nombre", label: "Nombre completo", widget: "string", required: true },
            { name: "cargo", label: "Cargo", widget: "string", required: true },
            { name: "fechaFijacion", label: "Fecha de fijación", widget: "string", required: true },
            { name: "fechaDesfijacion", label: "Fecha de desfijación", widget: "string", required: false },
            { name: "pdf", label: "URL del PDF de hoja de vida", widget: "string", required: true },
          ],
        },
      ],
    },
    {
      name: "supervision-vigilancia",
      label: "Supervisión y Vigilancia",
      file: "src/content/pages/transparencia/supervision-vigilancia.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-building-shield" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "entidades",
          label: "Entidades de control",
          widget: "list",
          label_singular: "Entidad",
          collapsed: true,
          summary: "{{fields.nombre}} — {{fields.control}}",
          fields: [
            { name: "nombre", label: "Nombre de la entidad", widget: "string", required: true },
            { name: "direccion", label: "Dirección", widget: "string", required: false },
            { name: "telefono", label: "Teléfono", widget: "string", required: false },
            { name: "email", label: "Correo electrónico", widget: "string", required: false },
            { name: "web", label: "Sitio web", widget: "string", required: false },
            { name: "control", label: "Tipo de control", widget: "string", required: true, hint: "Ej: Control fiscal, Control disciplinario, Control penal" },
          ],
        },
      ],
    },
    {
      name: "planes-mejoramiento",
      label: "Planes de Mejoramiento",
      file: "src/content/pages/transparencia/planes-mejoramiento.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-chart-line" },
        {
          name: "secciones",
          label: "Secciones / Documentos",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "desc", label: "Descripción", widget: "text", required: false },
            { name: "url", label: "URL del recurso", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false, hint: "Ej: fa-file-excel, fa-landmark" },
            { name: "tipo", label: "Tipo", widget: "select", options: ["xlsx", "pdf", "ext"], default: "xlsx" },
          ],
        },
      ],
    },
    {
      name: "plan-adquisiciones",
      label: "Plan Anual de Adquisiciones",
      file: "src/content/pages/transparencia/contratacion/plan-adquisiciones.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-cart-shopping" },
        { name: "secopUrl", label: "URL SECOP II (Plan Anual)", widget: "string", required: false },
        {
          name: "anios",
          label: "Planes por vigencia",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "docs",
              label: "Documentos del año",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "proyectos-inversion",
      label: "Programas y Proyectos de Inversión",
      file: "src/content/pages/transparencia/proyectos-inversion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-chart-line" },
        {
          name: "enlacesExternos",
          label: "Enlaces externos (consulta SPI, DNP, etc.)",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL externa", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
          ],
        },
        {
          name: "informes",
          label: "Informes de Proyectos de Inversión (por año)",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "docs",
              label: "Informes",
              widget: "list",
              label_singular: "Informe",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
        {
          name: "fichasEbi",
          label: "Fichas EBI (por año)",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          required: false,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "fichas",
              label: "Fichas EBI del año",
              widget: "list",
              label_singular: "Ficha",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
        { name: "fichasEbiNota", label: "Nota sobre Fichas EBI", widget: "text", required: false },
        {
          name: "resumenEjecutivo",
          label: "Resúmenes ejecutivos por proyecto",
          widget: "list",
          label_singular: "Resumen",
          collapsed: true,
          required: false,
          summary: "Proyecto {{fields.proyecto}}",
          fields: [
            { name: "proyecto", label: "Código BPIN del proyecto", widget: "string", required: true },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
        {
          name: "seguimientosSPI",
          label: "Seguimientos a la ejecución (SPI)",
          widget: "list",
          label_singular: "Seguimiento",
          collapsed: true,
          required: false,
          summary: "{{fields.proyecto}} — {{fields.periodo}}",
          fields: [
            { name: "proyecto", label: "Código BPIN", widget: "string", required: true },
            { name: "periodo", label: "Periodo", widget: "string", required: true, hint: "Ej: III Trimestre 2023" },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
      ],
    },
    {
      name: "ejecucion-contratos",
      label: "Publicación de la ejecución de contratos",
      file: "src/content/pages/transparencia/contratacion/ejecucion-contratos.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-contract" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "enlacesExternos",
          label: "Enlaces externos (SECOP I/II)",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL externa", widget: "string", required: true },
          ],
        },
        {
          name: "vigencias",
          label: "Documentos por vigencia",
          widget: "list",
          label_singular: "Vigencia",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "documentos",
              label: "Documentos",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "#{{fields.numero}} {{fields.titulo}}",
              fields: [
                { name: "numero", label: "Número", widget: "string", required: false },
                { name: "titulo", label: "Título", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "procedimientos-adquisicion",
      label: "Procedimientos y Políticas de Adquisición",
      file: "src/content/pages/transparencia/contratacion/procedimientos-adquisicion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-signature" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "documentos",
          label: "Documentos",
          widget: "list",
          label_singular: "Documento",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "tipo", label: "Tipo", widget: "select", options: ["manual", "instructivo", "guia", "resolucion"], default: "manual" },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
      ],
    },
    {
      name: "informes-legales",
      label: "Informes Legales (Control Interno)",
      file: "src/content/pages/transparencia/informes-legales.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-circle-check" },
        {
          name: "secciones",
          label: "Secciones por año",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Año", widget: "string", required: true, hint: "Ej: 2026, 2025" },
            {
              name: "docs",
              label: "Categorías de documentos",
              widget: "list",
              label_singular: "Categoría",
              collapsed: true,
              summary: "{{fields.cat}}",
              fields: [
                { name: "cat", label: "Nombre de la categoría", widget: "string", required: true },
                {
                  name: "items",
                  label: "Documentos",
                  widget: "list",
                  label_singular: "Documento",
                  collapsed: true,
                  summary: "{{fields.n}}",
                  fields: [
                    { name: "n", label: "Nombre", widget: "string", required: true },
                    { name: "u", label: "URL", widget: "string", required: true },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
