// ============================================================
// Campos compartidos para items de transparencia
// ============================================================

const itemFields = [
  { name: "num", label: "Número (ej: 1.1)", widget: "string", required: false },
  { name: "texto", label: "Texto del enlace", widget: "string", required: true },
  { name: "url", label: "URL", widget: "string", required: false, hint: "Dejar vacío si es solo etiqueta (label)" },
  { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external", "pdf", "xlsx", "label"], default: "internal" },
  {
    name: "children",
    label: "Sub-items (opcional)",
    widget: "list",
    label_singular: "Sub-item",
    collapsed: true,
    required: false,
    summary: "{{fields.num}} {{fields.texto}}",
    fields: [
      { name: "num", label: "Número", widget: "string", required: false },
      { name: "texto", label: "Texto", widget: "string", required: true },
      { name: "url", label: "URL", widget: "string", required: true },
      { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external", "pdf", "xlsx"], default: "internal" },
    ],
  },
];

export const transparencia = {
  name: "transparencia",
  label: "TRANSPARENCIA",
  files: [
    {
      name: "transparencia-principal",
      label: "Página de Transparencia",
      file: "src/content/pages/transparencia.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-eye" },
        { name: "introTexto", label: "Texto introductorio", widget: "text", required: true },
        { name: "ley1712Url", label: "URL del PDF Ley 1712", widget: "string", required: false },
        {
          name: "secciones",
          label: "Secciones de Transparencia",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.numero}}. {{fields.titulo}}",
          fields: [
            { name: "numero", label: "Número de sección", widget: "string", required: true },
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
            { name: "tituloUrl", label: "URL del título (opcional)", widget: "string", required: false },
            { name: "descripcion", label: "Descripción (opcional)", widget: "text", required: false },
            {
              name: "items",
              label: "Items",
              widget: "list",
              label_singular: "Item",
              collapsed: true,
              summary: "{{fields.num}} {{fields.texto}}",
              fields: itemFields,
            },
          ],
        },
      ],
    },
    {
      name: "directorio-entidades",
      label: "Directorio de Entidades",
      file: "src/content/pages/transparencia/directorio-entidades.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-building" },
        {
          name: "grupos",
          label: "Grupos de entidades",
          widget: "list",
          label_singular: "Grupo",
          collapsed: true,
          summary: "{{fields.nombre}} ({{fields.entidades.length}})",
          fields: [
            { name: "nombre", label: "Nombre del grupo", widget: "string", required: true },
            {
              name: "entidades",
              label: "Entidades",
              widget: "list",
              label_singular: "Entidad",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del sitio web", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "hojas-de-vida",
      label: "Publicación Hojas de Vida",
      file: "src/content/pages/transparencia/hojas-de-vida.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-id-card" },
        { name: "enlaceExterno", label: "URL enlace Presidencia", widget: "string", required: false },
        {
          name: "aspirantes",
          label: "Aspirantes",
          widget: "list",
          label_singular: "Aspirante",
          collapsed: true,
          summary: "{{fields.nombre}} — {{fields.cargo}}",
          fields: [
            { name: "nombre", label: "Nombre completo", widget: "string", required: true },
            { name: "cargo", label: "Cargo", widget: "string", required: true },
            { name: "fechaFijacion", label: "Fecha de fijación", widget: "string", required: true },
            { name: "fechaDesfijacion", label: "Fecha de desfijación", widget: "string", required: false },
            { name: "pdf", label: "URL del PDF de hoja de vida", widget: "string", required: true },
          ],
        },
      ],
    },
    {
      name: "supervision-vigilancia",
      label: "Supervisión y Vigilancia",
      file: "src/content/pages/transparencia/supervision-vigilancia.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-building-shield" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "entidades",
          label: "Entidades de control",
          widget: "list",
          label_singular: "Entidad",
          collapsed: true,
          summary: "{{fields.nombre}} — {{fields.control}}",
          fields: [
            { name: "nombre", label: "Nombre de la entidad", widget: "string", required: true },
            { name: "direccion", label: "Dirección", widget: "string", required: false },
            { name: "telefono", label: "Teléfono", widget: "string", required: false },
            { name: "email", label: "Correo electrónico", widget: "string", required: false },
            { name: "web", label: "Sitio web", widget: "string", required: false },
            { name: "control", label: "Tipo de control", widget: "string", required: true, hint: "Ej: Control fiscal, Control disciplinario, Control penal" },
          ],
        },
      ],
    },
    {
      name: "planes-mejoramiento",
      label: "Planes de Mejoramiento",
      file: "src/content/pages/transparencia/planes-mejoramiento.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-chart-line" },
        {
          name: "secciones",
          label: "Secciones / Documentos",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "desc", label: "Descripción", widget: "text", required: false },
            { name: "url", label: "URL del recurso", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false, hint: "Ej: fa-file-excel, fa-landmark" },
            { name: "tipo", label: "Tipo", widget: "select", options: ["xlsx", "pdf", "ext"], default: "xlsx" },
          ],
        },
      ],
    },
    {
      name: "plan-adquisiciones",
      label: "Plan Anual de Adquisiciones",
      file: "src/content/pages/transparencia/contratacion/plan-adquisiciones.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-cart-shopping" },
        { name: "secopUrl", label: "URL SECOP II (Plan Anual)", widget: "string", required: false },
        {
          name: "anios",
          label: "Planes por vigencia",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "docs",
              label: "Documentos del año",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "proyectos-inversion",
      label: "Programas y Proyectos de Inversión",
      file: "src/content/pages/transparencia/proyectos-inversion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-chart-line" },
        {
          name: "enlacesExternos",
          label: "Enlaces externos (consulta SPI, DNP, etc.)",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL externa", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
          ],
        },
        {
          name: "informes",
          label: "Informes de Proyectos de Inversión (por año)",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "docs",
              label: "Informes",
              widget: "list",
              label_singular: "Informe",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
        {
          name: "fichasEbi",
          label: "Fichas EBI (por año)",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          required: false,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "fichas",
              label: "Fichas EBI del año",
              widget: "list",
              label_singular: "Ficha",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
        { name: "fichasEbiNota", label: "Nota sobre Fichas EBI", widget: "text", required: false },
        {
          name: "resumenEjecutivo",
          label: "Resúmenes ejecutivos por proyecto",
          widget: "list",
          label_singular: "Resumen",
          collapsed: true,
          required: false,
          summary: "Proyecto {{fields.proyecto}}",
          fields: [
            { name: "proyecto", label: "Código BPIN del proyecto", widget: "string", required: true },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
        {
          name: "seguimientosSPI",
          label: "Seguimientos a la ejecución (SPI)",
          widget: "list",
          label_singular: "Seguimiento",
          collapsed: true,
          required: false,
          summary: "{{fields.proyecto}} — {{fields.periodo}}",
          fields: [
            { name: "proyecto", label: "Código BPIN", widget: "string", required: true },
            { name: "periodo", label: "Periodo", widget: "string", required: true, hint: "Ej: III Trimestre 2023" },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
      ],
    },
    {
      name: "ejecucion-contratos",
      label: "Publicación de la ejecución de contratos",
      file: "src/content/pages/transparencia/contratacion/ejecucion-contratos.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-contract" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "enlacesExternos",
          label: "Enlaces externos (SECOP I/II)",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL externa", widget: "string", required: true },
          ],
        },
        {
          name: "vigencias",
          label: "Documentos por vigencia",
          widget: "list",
          label_singular: "Vigencia",
          collapsed: true,
          summary: "{{fields.anio}}",
          fields: [
            { name: "anio", label: "Año", widget: "string", required: true },
            {
              name: "documentos",
              label: "Documentos",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "#{{fields.numero}} {{fields.titulo}}",
              fields: [
                { name: "numero", label: "Número", widget: "string", required: false },
                { name: "titulo", label: "Título", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "procedimientos-adquisicion",
      label: "Procedimientos y Políticas de Adquisición",
      file: "src/content/pages/transparencia/contratacion/procedimientos-adquisicion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-signature" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "documentos",
          label: "Documentos",
          widget: "list",
          label_singular: "Documento",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "tipo", label: "Tipo", widget: "select", options: ["manual", "instructivo", "guia", "resolucion"], default: "manual" },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
      ],
    },
    ...(function listadoInformes() {
      const make = (name, label, path, iconDefault) => ({
        name,
        label,
        file: `src/content/pages/transparencia/informes/${path}`,
        fields: [
          { name: "title", label: "Título", widget: "string", required: true },
          { name: "description", label: "Descripción SEO", widget: "text", required: false },
          { name: "icon", label: "Icono FontAwesome", widget: "string", default: iconDefault },
          { name: "intro", label: "Texto introductorio", widget: "text", required: false },
          {
            name: "informes",
            label: "Informes (listado cronológico)",
            widget: "list",
            label_singular: "Informe",
            collapsed: true,
            summary: "{{fields.titulo}}",
            fields: [
              { name: "titulo", label: "Título del informe", widget: "string", required: true, hint: "Incluir periodo (ej. 'Semestre I 2025', 'Vigencia 2023')" },
              { name: "url", label: "URL del archivo (PDF/XLSX)", widget: "string", required: true },
            ],
          },
        ],
      });
      return [
        make("informe-pormenorizado-ci", "Informe Pormenorizado del SCI", "informe-pormenorizado.json", "fa-file-lines"),
        make("evaluacion-independiente-sci", "Evaluación Independiente del SCI", "evaluacion-independiente-sci.json", "fa-magnifying-glass-chart"),
        make("seguimiento-plan-anticorrupcion", "Seguimiento al PAAC / PTEP / Mapa de Riesgos", "seguimiento-plan-anticorrupcion.json", "fa-shield-halved"),
        make("informes-software-legal", "Informes de Software Legal", "informes-software-legal.json", "fa-laptop-code"),
        make("rendicion-cuenta-fiscal-cgr", "Rendición Cuenta Fiscal CGR", "rendicion-cuenta-fiscal-cgr.json", "fa-file-invoice"),
      ];
    })(),
    {
      name: "relatoria",
      label: "Relatoría",
      file: "src/content/pages/transparencia/relatoria.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-book-open" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        { name: "criteriosSeleccion", label: "Criterios de selección", widget: "text", required: false },
        {
          name: "cta",
          label: "Botón CTA (buscador externo)",
          widget: "object",
          collapsed: true,
          required: false,
          fields: [
            { name: "texto", label: "Texto del botón", widget: "string", required: false },
            { name: "url", label: "URL destino", widget: "string", required: false },
            { name: "descripcion", label: "Descripción", widget: "text", required: false },
            { name: "external", label: "Es enlace externo", widget: "boolean", default: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-magnifying-glass" },
          ],
        },
        {
          name: "resolucion",
          label: "Resolución de creación",
          widget: "object",
          collapsed: true,
          required: false,
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: false },
            { name: "url", label: "URL del PDF", widget: "string", required: false, hint: "Dejar vacío si aún no está publicada" },
          ],
        },
      ],
    },
    {
      name: "evaluacion-auditoria-3ld",
      label: "Informes de Evaluación y Auditoría 3LD (catálogo OCI)",
      file: "src/content/pages/transparencia/informes/evaluacion-auditoria-3ld.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-layer-group" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "categorias",
          label: "Categorías de informes OCI",
          widget: "list",
          label_singular: "Categoría",
          collapsed: true,
          summary: "{{fields.numero}}. {{fields.titulo}}",
          fields: [
            { name: "numero", label: "Número", widget: "string", required: true, hint: "Dos dígitos, ej. 01, 05, 27" },
            { name: "titulo", label: "Título de la categoría", widget: "string", required: true },
            {
              name: "destino",
              label: "Destino del enlace",
              widget: "object",
              required: true,
              fields: [
                { name: "url", label: "URL destino", widget: "string", required: false, hint: "Vacío si el estado es 'proximamente'. Internos con slash inicial, externos URL completa." },
                { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external"], default: "internal" },
                { name: "estado", label: "Estado", widget: "select", options: ["disponible", "proximamente"], default: "proximamente", hint: "'disponible' activa el enlace; 'proximamente' muestra badge deshabilitado." },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "informes-organismos-ivc",
      label: "Informes a Organismos IVC (hub)",
      file: "src/content/pages/transparencia/informes-organismos-ivc.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-building-columns" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "enlaces",
          label: "Tarjetas / enlaces",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "descripcion", label: "Descripción", widget: "text", required: false },
            { name: "url", label: "URL", widget: "string", required: true, hint: "Internos: ruta con slash inicial. Externos: URL completa." },
            { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external"], default: "internal" },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
          ],
        },
      ],
    },
    // ============================================================
    // Lote R — Documentación y Archivos (5 páginas MEDIA)
    // ============================================================
    {
      name: "tablas-retencion",
      label: "Tablas de Retención Documental",
      file: "src/content/pages/transparencia/tablas-retencion.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-table-list" },
        {
          name: "versiones",
          label: "Versiones de las TRD",
          widget: "list",
          label_singular: "Versión",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Nombre de la versión", widget: "string", required: true, hint: "Ej: 'Versión 2 (Vigente)', 'Versión 1'" },
            {
              name: "docs",
              label: "Documentos",
              widget: "list",
              label_singular: "Documento",
              collapsed: true,
              summary: "{{fields.n}}",
              fields: [
                { name: "n", label: "Nombre", widget: "string", required: true },
                { name: "u", label: "URL", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    ...(function documentacionFactory() {
      const mk = (name, label, path, iconDefault) => ({
        name,
        label,
        file: `src/content/pages/transparencia/documentacion/${path}`,
        fields: [
          { name: "title", label: "Título", widget: "string", required: true },
          { name: "description", label: "Descripción SEO", widget: "text", required: false },
          { name: "icon", label: "Icono FontAwesome", widget: "string", default: iconDefault },
          { name: "intro", label: "Texto introductorio", widget: "text", required: false },
          {
            name: "informes",
            label: "Documentos",
            widget: "list",
            label_singular: "Documento",
            collapsed: true,
            summary: "{{fields.titulo}}",
            fields: [
              { name: "titulo", label: "Título", widget: "string", required: true },
              { name: "url", label: "URL", widget: "string", required: true },
            ],
          },
        ],
      });
      return [
        mk("esquema-publicacion", "Esquema de Publicación de la Información", "esquema-publicacion.json", "fa-table-cells"),
        mk("registro-publicaciones", "Registro de Publicaciones", "registro-publicaciones.json", "fa-clipboard-list"),
        mk("formato-grupos-etnicos", "Formato alternativo grupos étnicos/culturales", "formato-grupos-etnicos.json", "fa-users-rectangle"),
      ];
    })(),
    {
      name: "proteccion-datos",
      label: "Protección de Datos Personales",
      file: "src/content/pages/transparencia/documentacion/proteccion-datos.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-shield" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "documentos",
          label: "Política vigente",
          widget: "list",
          label_singular: "Documento",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL", widget: "string", required: true },
            { name: "tipo", label: "Tipo", widget: "select", options: ["pdf", "xlsx"], default: "pdf" },
          ],
        },
        {
          name: "enlacesExternos",
          label: "Consultas externas",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "descripcion", label: "Descripción", widget: "text", required: false },
            { name: "url", label: "URL", widget: "string", required: true },
            { name: "icon", label: "Icono", widget: "string", required: false },
          ],
        },
      ],
    },
    // ============================================================
    // Lote M5 — Reporte Austeridad en el Gasto (último de M)
    // ============================================================
    {
      name: "reporte-austeridad-gasto",
      label: "Reporte Austeridad en el Gasto",
      file: "src/content/pages/transparencia/reporte-austeridad-gasto.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-money-bill-trend-up" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "informes",
          label: "Reportes semestrales",
          widget: "list",
          label_singular: "Reporte",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true, hint: "Incluir semestre/año en el título, ej. 'Reporte de Austeridad — II Semestre 2024'" },
            { name: "url", label: "URL del PDF", widget: "string", required: true },
          ],
        },
      ],
    },
    // ============================================================
    // Lote M4 — Gestión Documental (4 páginas Ley 1712)
    // ============================================================
    ...(function gestionDocumental() {
      const mk = (name, label, path, iconDefault) => ({
        name,
        label,
        file: `src/content/pages/transparencia/${path}`,
        fields: [
          { name: "title", label: "Título", widget: "string", required: true },
          { name: "description", label: "Descripción SEO", widget: "text", required: false },
          { name: "icon", label: "Icono FontAwesome", widget: "string", default: iconDefault },
          { name: "intro", label: "Texto introductorio", widget: "text", required: false },
          {
            name: "informes",
            label: "Documentos",
            widget: "list",
            label_singular: "Documento",
            collapsed: true,
            summary: "{{fields.titulo}}",
            fields: [
              { name: "titulo", label: "Título del documento", widget: "string", required: true },
              { name: "url", label: "URL del archivo", widget: "string", required: true },
            ],
          },
        ],
      });
      return [
        mk("indice-informacion-clasificada", "Índice de Información Clasificada y Reservada", "indice-informacion-clasificada.json", "fa-lock"),
        mk("programa-gestion-documental", "Programa de Gestión Documental", "programa-gestion-documental.json", "fa-folder-tree"),
        mk("procedimientos-decisiones", "Procedimientos para tomar decisiones", "procedimientos-decisiones.json", "fa-diagram-project"),
        mk("formatos-contratos-pliegos-tipo", "Formatos o modelos de contratos / pliego tipo", "formatos-contratos-pliegos-tipo.json", "fa-file-contract"),
      ];
    })(),
    // ============================================================
    // Lote M3 — Decretos de estructura, salarios, leyes marco
    // ============================================================
    {
      name: "decretos-estructura",
      label: "Decretos de estructura, salarios, leyes marco y otros",
      file: "src/content/pages/transparencia/decretos-estructura.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-gavel" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "secciones",
          label: "Secciones temáticas de decretos",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título de la sección", widget: "string", required: true, hint: "Ej: 'Decretos de modificación de la estructura', 'Decretos salariales por vigencia'" },
            { name: "descripcion", label: "Descripción breve", widget: "text", required: false },
            {
              name: "decretos",
              label: "Decretos",
              widget: "list",
              label_singular: "Decreto",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "numero", label: "Número", widget: "string", required: true, hint: "Ej: 4173, 0985, 611" },
                { name: "anio", label: "Año", widget: "string", required: false },
                { name: "nombre", label: "Nombre completo", widget: "string", required: true },
                { name: "url", label: "URL del PDF", widget: "string", required: true },
                { name: "nota", label: "Nota de verificación", widget: "text", required: false, hint: "Uso para enlaces heredados que requieran revisión por Jurídica." },
              ],
            },
          ],
        },
      ],
    },
    // ============================================================
    // Lote M2 — Sede/Horarios + Proyectos normas comentarios
    // ============================================================
    {
      name: "sede-horarios",
      label: "Sede y Horarios",
      file: "src/content/pages/transparencia/sede-horarios.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-location-dot" },
        {
          name: "sede",
          label: "Datos de la sede",
          widget: "object",
          fields: [
            { name: "nombre", label: "Nombre de la sede", widget: "string", required: true },
            { name: "direccion", label: "Dirección (calle y número)", widget: "string", required: true },
            { name: "piso", label: "Piso / oficina", widget: "string", required: false },
            { name: "ciudad", label: "Ciudad", widget: "string", required: true },
            { name: "codigoPostal", label: "Código postal", widget: "string", required: false },
          ],
        },
        {
          name: "horario",
          label: "Horario de atención",
          widget: "object",
          fields: [
            { name: "dias", label: "Días", widget: "string", required: true, hint: "Ej: 'Lunes a viernes'" },
            { name: "inicio", label: "Hora inicio", widget: "string", required: true },
            { name: "fin", label: "Hora fin", widget: "string", required: true },
            { name: "nota", label: "Nota adicional (feriados, excepciones)", widget: "string", required: false },
          ],
        },
        {
          name: "contacto",
          label: "Contacto",
          widget: "object",
          fields: [
            { name: "telefono", label: "Teléfono principal", widget: "string", required: true },
            { name: "extension", label: "Extensión", widget: "string", required: false },
            { name: "email", label: "Correo electrónico", widget: "string", required: true },
            { name: "lineaGratuita", label: "Línea gratuita 018000", widget: "string", required: false },
          ],
        },
        {
          name: "mapa",
          label: "Mapa (opcional)",
          widget: "object",
          required: false,
          collapsed: true,
          fields: [
            { name: "embedUrl", label: "URL de embed de Google Maps", widget: "string", required: false, hint: "Si se llena, se muestra el mapa embebido." },
            { name: "lat", label: "Latitud", widget: "string", required: false },
            { name: "lng", label: "Longitud", widget: "string", required: false },
          ],
        },
      ],
    },
    {
      name: "proyectos-normas-comentarios",
      label: "Proyectos de Normas para Comentarios",
      file: "src/content/pages/transparencia/proyectos-normas-comentarios.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-pen" },
        { name: "intro", label: "Texto introductorio", widget: "text", required: false },
        {
          name: "enlacesExternos",
          label: "Canales externos de consulta",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "descripcion", label: "Descripción", widget: "text", required: false },
            { name: "url", label: "URL externa", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
          ],
        },
        {
          name: "proyectosLocales",
          label: "Proyectos normativos de la Agencia ITRC",
          widget: "list",
          label_singular: "Proyecto",
          collapsed: true,
          required: false,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título del proyecto", widget: "string", required: true },
            { name: "tipo", label: "Tipo de norma", widget: "string", required: false, hint: "Ej: Resolución, Circular, Decreto" },
            { name: "fechaApertura", label: "Fecha de apertura", widget: "string", required: false },
            { name: "fechaCierre", label: "Fecha de cierre", widget: "string", required: false },
            { name: "estado", label: "Estado", widget: "select", options: ["abierto", "cerrado"], default: "abierto" },
            { name: "urlProyecto", label: "URL del proyecto (PDF)", widget: "string", required: false },
            { name: "urlFormularioComentarios", label: "URL del formulario de comentarios", widget: "string", required: false },
            { name: "resultado", label: "URL del documento con resultado / consolidado de comentarios", widget: "string", required: false },
          ],
        },
      ],
    },
    // ============================================================
    // Lote M1 — Saneamiento CMS (JSONs huérfanos preexistentes)
    // ============================================================
    {
      name: "decreto-unico",
      label: "Decreto Único Reglamentario",
      file: "src/content/pages/transparencia/decreto-unico.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-lines" },
        {
          name: "documentos",
          label: "Documentos",
          widget: "list",
          label_singular: "Documento",
          collapsed: true,
          summary: "{{fields.nombre}}",
          fields: [
            { name: "nombre", label: "Nombre", widget: "string", required: true },
            { name: "url", label: "URL", widget: "string", required: true },
            { name: "tipo", label: "Tipo", widget: "select", options: ["pdf", "external", "xlsx"], default: "pdf" },
          ],
        },
      ],
    },
    {
      name: "informacion-mujeres",
      label: "Información para Mujeres",
      file: "src/content/pages/transparencia/informacion-mujeres.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-venus" },
        {
          name: "secciones",
          label: "Secciones temáticas",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título de la sección", widget: "string", required: true },
            {
              name: "links",
              label: "Enlaces",
              widget: "list",
              label_singular: "Enlace",
              collapsed: true,
              summary: "{{fields.nombre}}",
              fields: [
                { name: "nombre", label: "Nombre del enlace", widget: "string", required: true },
                { name: "url", label: "URL", widget: "string", required: true },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "defensa-publica",
      label: "Defensa Pública y Prevención del Daño Antijurídico",
      file: "src/content/pages/transparencia/defensa-publica.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-shield-halved" },
        {
          name: "enlaces",
          label: "Recursos / enlaces",
          widget: "list",
          label_singular: "Enlace",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL", widget: "string", required: true, hint: "Internos con slash inicial, externos URL completa, PDFs URL completa." },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
            { name: "tipo", label: "Tipo", widget: "select", options: ["internal", "external", "pdf"], default: "external" },
          ],
        },
      ],
    },
    {
      name: "normatividad-especial",
      label: "Normatividad Especial",
      file: "src/content/pages/transparencia/normatividad-especial.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-circle-check" },
        {
          name: "secciones",
          label: "Secciones",
          widget: "list",
          label_singular: "Sección",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Título", widget: "string", required: true },
            { name: "url", label: "URL destino", widget: "string", required: true },
            { name: "icon", label: "Icono FontAwesome", widget: "string", required: false },
          ],
        },
      ],
    },
    {
      name: "tramites",
      label: "Trámites",
      file: "src/content/pages/transparencia/tramites.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-clipboard-list" },
        { name: "texto", label: "Texto explicativo", widget: "text", required: true, hint: "Texto principal sobre trámites (o ausencia de ellos)." },
        { name: "costosUrl", label: "URL a Resolución de Costos", widget: "string", required: false, hint: "Resolución que fija costos de copias, certificaciones, etc." },
      ],
    },
    {
      name: "registro-activos",
      label: "Registro de Activos de Información",
      file: "src/content/pages/transparencia/registro-activos.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-database" },
        { name: "pdfUrl", label: "URL del archivo", widget: "string", required: true, hint: "Normalmente un XLSX con el registro completo." },
        { name: "pdfNombre", label: "Nombre del archivo (para mostrar)", widget: "string", required: true },
        { name: "tipoArchivo", label: "Tipo de archivo", widget: "select", options: ["pdf", "xlsx", "xls", "docx"], default: "xlsx" },
      ],
    },
    {
      name: "informes-legales",
      label: "Informes Legales (Control Interno)",
      file: "src/content/pages/transparencia/informes-legales.json",
      fields: [
        { name: "title", label: "Título", widget: "string", required: true },
        { name: "description", label: "Descripción SEO", widget: "text", required: false },
        { name: "icon", label: "Icono FontAwesome", widget: "string", default: "fa-file-circle-check" },
        {
          name: "secciones",
          label: "Secciones por año",
          widget: "list",
          label_singular: "Año",
          collapsed: true,
          summary: "{{fields.titulo}}",
          fields: [
            { name: "titulo", label: "Año", widget: "string", required: true, hint: "Ej: 2026, 2025" },
            {
              name: "docs",
              label: "Categorías de documentos",
              widget: "list",
              label_singular: "Categoría",
              collapsed: true,
              summary: "{{fields.cat}}",
              fields: [
                { name: "cat", label: "Nombre de la categoría", widget: "string", required: true },
                {
                  name: "items",
                  label: "Documentos",
                  widget: "list",
                  label_singular: "Documento",
                  collapsed: true,
                  summary: "{{fields.n}}",
                  fields: [
                    { name: "n", label: "Nombre", widget: "string", required: true },
                    { name: "u", label: "URL", widget: "string", required: true },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
